V-Sekai/v-sekai-game

.github/actions/godot-deps/action.yml
.github/workflows/vsk_linux_builds.yml

Needed to keep the builds green.

Remove libgodot until the build is fixed

---

.github/actions/godot-cache/action.yml
.github/actions/godot-deps/action.yml

The Godot dependency action reference in the GitHub Actions workflow has been updated to use the latest commit from the "groups-4.x" branch.
Enable always upload cache.

Update Godot dependency action reference

---

.github/workflows/builds.yml

This commit adds new jobs to the builds.yml file for deploying the Linux editor on both Windows and Linux platforms. The deployments include specific configurations and paths for each platform.

Add Linux editor deployment for Windows and Linux platforms

---

.github/workflows/builds.yml

Add an export step timeout for exporting because sometime it hangs.

Update builds.yml: limit timeout for Linux export

---

addons/sar1_vr_manager/vr_origin.gd
addons/vsk_manager/vsk_game_flow_manager.gd

- Update ownership of `desktop_viewport` and `desktop_camera` to `vr_camera`
- Remove duplicate viewports by checking if the new viewport's parent is not null, then removing it before adding the new viewport

Enable opengl mode WIP

---

.github/actions/godot-deps/action.yml

Still working on a Godot Engine 4.2 migration. Documentation xml changed incompatibility. 
Posted a fix for the magenta viewport copy of xr bug. `https://github.com/godotengine/godot/issues/66247#issuecomment-1646756995`
Also works on the mac after the fix. 
One more thing, compatibility opengl mode works too on the mac.

Update Godot to be groups-4.2.2023-07-23T155335Z

---

.github/actions/godot-deps/action.yml

The Godot dependency reference has been updated to "groups-4.2.2023-07-24T041040Z" in the GitHub Actions configuration file.

Update Godot dependency reference

---

.github/actions/godot-deps/action.yml

Update the groups groups-4.2.2023-09-12T231311Z.

---

project.godot

This references an addon that no longer exists, which causes errors in the project.
I noticed it was removed a while back, but the setting in the Autoload tab was not.

Remove DebugMenu from the Autoload

---

addons/vsk_menu/main_menu/title_screen.tscn

I noticed that the exit dialog didn't have any text, despite there being a string for it on `menu_strings.csv`.
I've also adjusted the maximum size to a more reasonable limit. It was way too big by default.

Add exit message to quit dialog

---

addons/input_manager/input_manager.gd

Tested by deleting `%APPDATA%/Roaming/Godot/app_userdata/V-Sekai Game/settings.cfg` and seeing that it sets the default value correctly.
Edited:
Fixes #253

mouse_sensitivity = 5

---

addons/vsk_entities/vsk_player.tscn

Removed the `PlayerPickupController` node on `vsk_player.tscn`.
This referenced a missing script, which made it impossible to open the scene.
I'm sure that it can be added back later on, if necessary.

Remove PlayerPickup dependency

---

addons/sar1_vr_manager/vr_origin.gd

For some reason, when I entered a server or went back to the menu, a new `DesktopViewport` would be generated.
I added a check to see if `VSKGameFlowManager` already has a `DesktopViewport` and if it does, simply use its camera.

Ensure that there is only one DesktopViewport

---

.github/workflows/builds.yml

This commit adds the necessary code to include the GitHub token for creating releases. This will allow the workflow to successfully create draft and pre-release versions of the project.

Add GitHub token for release creation

---

.github/workflows/builds.yml

The commit updates the GitHub token used in the builds.yml file. The previous token has been replaced with a new one named VSEKAI_GITHUB_TOKEN. This change ensures that the correct token is used for authentication during the build process.

Update GitHub token in builds.yml

---

addons/vsk_manager/vsk_game_flow_manager.gd
addons/vsk_menu/menu_view_controller.gd

Added an input event on the menu view controller so that, when `ui_cancel` is pressed, it calls `back_button_pressed()`.
It also checks for `view_controller_stack`'s size so that I don't accidentally destroy the title screen.
I also removed some code on the game flow manager that felt redundant, as it only returned to the title screen while already being there.
Closes #251

Return to previous menu when ui_cancel is pressed

---

.github/workflows/builds.yml

Use [groups-4.2.2023-11-29T013556Z](https://github.com/V-Sekai/godot/releases/tag/groups-4.2.2023-11-29T013556Z)

Update builds.yml to use groups-4.2.2023-11-29T013556Z

---

addons/godot-xr-tools/assets/player_body.gd

Fix error
`SCRIPT ERROR: Parse Error: Annotation "@icon" must be at the top of the script, before "extends" and "class_name".
at: GDScript::reload (res://addons/godot-xr-tools/assets/player_body.gd:4)`

Fix player_body.gd annotation

---

.github/workflows/build.yaml

Add hour/minute/seconds to avoid tag name collisions on rebuilds.

Fix timestamp tag

---

addons/godot_uro/godot_uro_api.gd
addons/godot_uro/godot_uro_helper.gd

https://github.com/V-Sekai/uro/pull/106
Adds API key to authenticate signup requests

Add API key signup authentication
