.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_proposal.yml
Add a template for bugs and proposals to match the other repo.
=> Add issue templates.

.github/workflows/build-project-iphone-arm64.yml, .github/workflows/build-project-linux-86_64.yml, .github/workflows/build-project-macos-86_64.yml
=> Try making builds for ios and mac.

.github/actions/godot-deps/action.yml, .github/workflows/vsk_linux_builds.yml
Build libgodot with the build system.
=> Trial libgodot and also generate build artifacts.

.github/workflows/vsk_linux_builds.yml
Use a different cache key to enable caching.
=> Update vsk_linux_builds.yml to use a different cache key

.github/workflows/vsk_linux_builds.yml
=> Format actions.

.github/actions/godot-deps/action.yml
=> Update to the latest master.

.github/workflows/vsk_linux_builds.yml
=> Build gdextension and libgodot.

.github/actions/godot-deps/action.yml, .github/workflows/vsk_linux_builds.yml, .github/workflows/vsk_test_report.yml
=> Update godot master.

.gitmodules
Restore splerger. Used for uploading maps.
=> Add splerger.

.github/actions/godot-deps/action.yml
=> Update action.yml for csg godot

.github/actions/godot-deps/action.yml
=> Update action.yml to use the latest forked Godot Engine

.github/workflows/builds.yml
=> Change the deployment to an editor

.github/actions/godot-deps/action.yml
Update V-Sekai/godot to groups-4.x.2023-05-22T141200Z
=> Update Godot Engine

project.godot
Avoid splash image so that we can choose later what splashes to add.
=> Avoid splash image

project.godot
We dual mode use v-sekai for both desktop and xr.
=> Remove the xr start alert

addons/vsk_manager/vsk_startup_manager.gd
- Refactored the startup manager code to improve readability and organization.
- Updated the commandline argument parsing logic for better handling of arguments.
- Removed unnecessary comments and unused variables.
=> Refactor startup manager and commandline argument parsing

.github/actions/godot-deps/action.yml, .github/workflows/builds.yml, project.godot
The commit updates the Godot dependency version in the action.yml file from groups-4.x.2023-07-09T024140Z to groups-4.1.2023-07-17T011131Z, allowing for compatibility with the latest changes in the repository v-sekai/godot.
=> Update Godot dependency version to groups-4.1.2023-07-17T011131Z

.github/actions/godot-deps/action.yml
- Update the ref value for the repository to groups-4.1.2023-07-21T031218Z
=> Update godot-deps action.yml

addons/Godot-MToon-Shader/.gitrepo, addons/network_manager/network_manager.gd, addons/vrm/.gitrepo
=> Avoid physics error

.github/actions/godot-deps/action.yml
Update the Godot Engine build for V-Sekai-game
=> Update Godot Engine build

.github/workflows/builds.yml
The commit refactors the build workflow by changing the name to "V-Sekai Builds". Additionally, it adds a new step for creating releases. The release step downloads artifacts, creates a release with the corresponding tag name, and uploads release assets.
=> Refactor build workflow and add release functionality

.github/actions/godot-deps/action.yml
Update to ref: `groups-4.2.2023-08-30T150424Z`
=> Update godot engine.

project.godot
=> Depth buffer doesn't work on the meta hardware.

.github/workflows/builds.yml
=> Fix typo in builds.yml: change "pre-release" to "prerelease".

.github/workflows/builds.yml
This reverts commit 4d021301fffe98c12c2d7cf4552057bd9b892689.
=> Revert "Merge pull request #272 from V-Sekai/prerelease"

project.godot
=> Update rendering settings to be single-safe.

addons/vrm/import_vrm.gd, addons/vsk_avatar/vsk_avatar_definition_editor.gd, addons/vsk_map/map_callback.gd, addons/vsk_map/vsk_map_definition_editor.gd, addons/vsk_vrm_avatar_tool/vsk_vrm_avatar_converter_editor.gd, addons/vsk_vrm_avatar_tool/vsk_vrm_avatar_functions.gd
Debugging vrm1 export.
```
res://addons/vsk_vrm_avatar_tool/vsk_vrm_avatar_functions.gd:115 - Invalid set index 'stiffness_force' (on base: 'GLTFDocumentExtension (VRMC_springBone.gd)') with value of type 'PackedFloat64Array'.
Transient parent has another exclusive child.
res://addons/vsk_vrm_avatar_tool/vsk_vrm_avatar_converter_editor.gd:59 - Cannot call method 'set_owner' on a null value.
```
=> Add VRM1 avatar export

addons/vrm/.gitrepo, addons/vrm/1.0/VRMC_materials_mtoon.gd, addons/vrm/1.0/VRMC_node_constraint.gd, addons/vrm/1.0/VRMC_vrm.gd, addons/vrm/node_constraint/bone_node_constraint.gd, addons/vrm/vrm_utils.gd
=> git subrepo pull (merge) addons/vrm

.github/workflows/builds.yml
Fixes: https://github.com/V-Sekai/v-sekai-game/issues/313
=> Cleanup builds

.github/install_vulkan_sdk_macos.sh, .github/workflows/builds.yml
See https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
=> Add macos editor builds. **Editor builds only**

addons/unidot/.gitrepo, addons/unidot/LICENSE.txt, addons/unidot/asset_meta.gd, addons/unidot/package_import_dialog.gd, addons/unidot/plugin.gd, addons/unidot/post_import_unity_model.gd, addons/unidot/unity_asset_adapter.gd, addons/unidot/unity_object_adapter.gd, addons/unidot/unitypackagefile.gd
Update unidot to the latest changes.
=> git subrepo pull addons/unidot

README.md
=> Add a caution section.

.github/workflows/builds.yml
Use 4.2.2023-11-25T162935Z of Godot groups-4.2
=> Update GODOT_REF in builds.yml to use the latest changes.

addons/vsk_manager/vsk_network_manager.gd, addons/vsk_manager/vsk_shard_manager.gd, addons/vsk_menu/shard_browser.gd
Updates the VSKShardManager to use full await and callback support. Should improve the readability of the program flow when it comes to shard registration.
=> Update VSKShardManager to use more modern coroutines.

addons/vsk_entities/vsk_player.tscn, addons/vsk_entities/vsk_player_v2.tscn, addons/vsk_manager/multiplayer/vsk_player_spawner.tscn, addons/vsk_manager/vsk_audio_manager.gd, addons/vsk_manager/vsk_game_flow_manager.gd, addons/vsk_manager/vsk_manager_plugin.gd, addons/vsk_manager/vsk_map_manager.gd, addons/vsk_manager/vsk_multiplayer_manager.gd, addons/vsk_manager/vsk_network_manager.gd, addons/vsk_manager/vsk_startup_manager.gd, addons/vsk_menu/create_server.gd, addons/vsk_menu/loading_screen.gd, project.godot
This is a WIP draft for the overhaul to the multiplayer system designed to make full use of Godot's own inbuilt MultiplayerAPI. The new system can be toggled via a feature flag in the project settings and should eventually replace the old one.
=> VSKMultiplayerManager

addons/sar1_vr_manager/components/lasso_snapping/snapping_point.gd
Update addons/sar1_vr_manager/components/lasso_snapping/snapping_point.gd compile.
=> Update snapping_point.gd so it extends RigidBody3D

README.md
https://github.com/V-Sekai/world-godot/issues/43
=> Add PeaZip as suggested extractor for macOS

addons/godot-xr-tools/functions/function_pickup.gd, addons/godot-xr-tools/functions/function_pointer.gd, addons/godot-xr-tools/functions/function_teleport.gd, addons/godot-xr-tools/functions/movement_provider.gd, addons/godot-xr-tools/objects/climbable.gd, project.godot
- Move icon annotations 
- Disable missing telemetry.gd addon
=> Fix icon annotations and telemetry.gd errors

addons/vsk_avatar/avatar_display.gd, addons/vsk_avatar/avatar_loader.gd, addons/vsk_avatar/vsk_avatar_definition_editor.gd, addons/vsk_editor/vsk_editor.gd, addons/vsk_editor/vsk_editor_plugin.gd, addons/vsk_editor/vsk_login_editor_control.gd, addons/vsk_entities/extensions/player_info_tag_controller.gd, addons/vsk_entities/extensions/player_movement/xr_controller/xr_controller_movement_direct.gd, addons/vsk_entities/extensions/player_movement/xr_controller/xr_controller_movement_jump.gd, addons/vsk_entities/extensions/player_movement/xr_controller/xr_controller_movement_provider.gd, addons/vsk_entities/extensions/player_movement/xr_controller/xr_controller_movement_turn.gd, addons/vsk_entities/extensions/player_snapshot_interpolation.gd, addons/vsk_entities/extensions/player_xr_origin.gd, addons/vsk_entities/extensions/tracker_space.gd, addons/vsk_importer_exporter/vsk_exporter.gd, addons/vsk_manager/vsk_account_manager.gd, addons/vsk_manager/vsk_asset_manager.gd, addons/vsk_manager/vsk_audio_manager.gd, addons/vsk_manager/vsk_avatar_manager.gd, addons/vsk_manager/vsk_game_flow_manager.gd, addons/vsk_manager/vsk_map_manager.gd, addons/vsk_manager/vsk_multiplayer_manager.gd, addons/vsk_manager/vsk_startup_manager.gd
#474 #476
This PR rewrites all `assert` checks into conditional statements.
There are two third party addons using `assert` left unchanged:
https://github.com/V-Sekai/v-sekai-game/blob/611341619df6ce4743a0325061c50ed0d736e347/addons/splerger/split_splerger.gd#L265-L267
https://github.com/V-Sekai/v-sekai-game/blob/611341619df6ce4743a0325061c50ed0d736e347/addons/vrm/1.0/VRMC_vrm.gd#L646
https://github.com/V-Sekai/v-sekai-game/blob/611341619df6ce4743a0325061c50ed0d736e347/addons/vrm/node_constraint/bone_node_constraint.gd#L180
PR was tested on **debug** and **release** exports:
Avatar loads in both versions and there are no visible regressions.
=> Rewrite asserts into conditional statements

addons/canvas_plane/canvas_3d.gd
`canvas_3d.gd` was deleted by https://github.com/V-Sekai/v-sekai-game/commit/965c969f86e8e828ebd6faf1619beecdd93f6638.
This causes error `SCRIPT ERROR: Parse Error: "spatial_canvas_const" is a constant but does not contain a type.` in [canvas_3d_anchor.gd](https://github.com/V-Sekai/v-sekai-game/blob/main/addons/canvas_plane/canvas_3d_anchor.gd).
Restoring the file fixes it.
=> Restore deleted canvas_3d.gd

CODEBASE.md, README.md
Improves documentation with a code map.
Addons that need review are marked with :warning: symbol.
=> Add codebase documentation

.pre-commit-config.yaml, addons/godot_uro/godot_uro_helper.gd
=> Add code lint sample

.pre-commit-config.yaml, addons/canvas_plane/canvas_3d.gd.uid, addons/godot-xr-tools/hands/animations/left/hand_blend_tree.tres, addons/godot-xr-tools/hands/animations/right/hand_blend_tree.tres, addons/godot_uro/http_pool.gd, addons/vsk_entities/extensions/infotag.tscn, project.godot
=> Lint http_pool.gd

.pre-commit-config.yaml, addons/vsk_importer_exporter/vsk_avatar_validator.gd, addons/vsk_importer_exporter/vsk_exporter.gd, addons/vsk_importer_exporter/vsk_importer.gd, addons/vsk_importer_exporter/vsk_map_validator.gd
=> Remove vsk_importer_exporter special case.

.github/workflows/code_style.yaml, .github/workflows/custom_linter.sh, addons/canvas_plane/canvas_3d.gd
#474 #475
Add script to check usage of **assert()** and **printerr()**
=> Add linter to check assert/printerr

docker/build-project/build.sh
#500
Fixes rendering error caused by missing ".html" extension and remove redundant folder  nesting in Web zip
=> Fix web export build
